name: Build & Test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build_and_test:
    name: Build Application and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm test
